import express from "express";
import { z } from "zod";
import { authenticate, authorize } from "../middleware/auth.middleware.js";
import { validate } from "../middleware/validate.middleware.js";
import { listQuotations, getQuotation, createQuotation, updateQuotation, deleteQuotation, sendQuotation, approveQuotation, rejectQuotation, convertQuotation } from "../controllers/quotation.controller.js";
const orderPayload = z.object({ addressId: z.string().uuid(), rentalPeriodId: z.string().uuid(), pickupType: z.enum(["STORE_PICKUP", "HOME_DELIVERY"]), startDate: z.coerce.date(), endDate: z.coerce.date() });
const patchPayload = z.object({ expiresAt: z.coerce.date().optional(), status: z.enum(["DRAFT", "PENDING_PAYMENT", "CONFIRMED", "READY_FOR_PICKUP", "PICKED_UP", "ACTIVE", "RETURN_REQUESTED", "RETURNED", "COMPLETED", "CANCELLED"]).optional() });
const router = express.Router();
router.use(authenticate);
router.get("/", listQuotations);
router.get("/:id", getQuotation);
router.post("/", createQuotation);
router.patch("/:id", authorize("ADMIN"), validate(z.object({ body: patchPayload })), updateQuotation);
router.delete("/:id", deleteQuotation);
router.post("/:id/send", sendQuotation);
router.post("/:id/approve", authorize("ADMIN"), approveQuotation);
router.post("/:id/reject", authorize("ADMIN"), rejectQuotation);
router.post("/:id/convert-order", validate(z.object({ body: orderPayload })), convertQuotation);
export default router;
