import express from "express";
import { authenticate, authorize } from "../middleware/auth.middleware.js";
import { getDashboard, getRevenue, getRentals, getDeposits, getLateFees, getStatistics } from "../controllers/dashboard.controller.js";
const router = express.Router();
router.use(authenticate, authorize("ADMIN"));
router.get("/", getDashboard);
router.get("/revenue", getRevenue);
router.get("/rentals", getRentals);
router.get("/deposits", getDeposits);
router.get("/late-fees", getLateFees);
router.get("/statistics", getStatistics);
export default router;
