import express from "express";
import { authenticate } from "../middleware/auth.middleware.js";
import { validate } from "../middleware/validate.middleware.js";
import { profileSchema, avatarSchema } from "../validations/api.validations.js";
import { getProfile, updateProfile, updateAvatar } from "../controllers/profile.controller.js";
const router = express.Router();
router.use(authenticate);
router.get("/", getProfile);
router.patch("/", validate(profileSchema), updateProfile);
router.patch("/avatar", validate(avatarSchema), updateAvatar);
export default router;
